data_loader: blender
object_name: chair
samples_dir: samples
scene_dir: datasets/nerf_synthetic/chair
scene_type: synthetic
stage_1:
  train_iters_cont: 300000
  training_iters: 200000
stage_2:
  training_iters_a: 400000
  training_iters_b: 100000
weights_dir: weights
