data_loader : "llff"
scene_type : "real360"
object_name : "gardenvase"
scene_dir : "datasets/nerf_real_360/gardenvase"
weights_dir : "weights"
samples_dir : "samples"

point_grid_size: 128
num_test_frames: 3
train_on_test_frames: False

stage_1:
  training_iters : 300000
  train_iters_cont : 300000

stage_2:
  training_iters_a : 400000
  training_iters_b : 100000